### ISSUE TITLE
Tiers' Don't Display

### ISSUE THREAD

**Issue by lunarrvxx** [Netiyiy/TierTagger#12]
I found this issue when I downloaded the mod where tiers, no matter what category, do not display. I've activated show unranked to confirm that people I'm testing the mod on are tested, and have tested it on multiple friends who are confirmed to be tested and are on the tierlist with no bans or punishments and the tiers do not display. I can use the search function, however it only works on known player, using it on unknown players causes the game to crash, which is an unrelated issue. I have similar issues with the Totem Viewer mod, where the other persons totems do not display in the nametag. I believe I have no conflicts in my modpack but I will gladly send it if needed.

**Comment by uku3lig** [comment]
update your mod
