### ISSUE TITLE
Tier tagger only showing vanilla tiers.

### ISSUE THREAD

**Issue by pqvo13** [Netiyiy/TierTagger#13]
Vanilla tiers only thing that actually works, even if you swap to like nethpot and make sure the player is tested in nethpot nothing pops up.

**Comment by uku3lig** [comment]
thanks for the report! could you please provide me with your minecraft version, the version of tiertagger you are using and if possible a logfile?

**Comment by pqvo13** [comment]
Yeah, sorry for such a delayed response. The version I was on was 1.20.1
and the tier tagger version was 1.7-1.20.1. Unfortunately I can't provide a
logfile.

**Comment by pqvo13** [comment]
Sorry but im wondering has it been resolved or is it still in progress?

**Comment by uku3lig** [comment]
it seems that doing `?count=32767` to get the whole tier list doesn't work anymore (except on vanilla for some unknown reason?)

@quadratickid was anything changed for this to be broken?

**Comment by pqvo13** [comment]
just let me know if you guys fix it, thanks!

**Comment by uku3lig** [comment]
upon further investigation, it seems that vanilla for some unknown reason works fine with `count=32767`, but other modes (tested only on `neth_pot`) only accept a `count` corresponding to the amount of people in the list (in this case, 1068). surprisingly, doing something like `from=1050&count=25` (anologous to what the website would do) still returns a 503 ...

**Comment by QuadraticKid** [comment]
Requesting 32 thousand users from an endpoint is EXTREMELY abusive, and the 503 errors are caused by server overload due to you guys.
I have limited the api/tier endpoint to 50 players per query, spamming this endpoint will result in further restrictions to the API.

Please consider using something that loads on the fly, such as requesting a tier of a user with /api/rankings/<uuid> when they come into render distance. Please also cache this locally for at lease some duration as to not spam the server.

**Comment by xyzeva** [comment]
> Requesting 32 thousand users from an endpoint is EXTREMELY abusive, and the 503 errors are caused by server overload due to you guys. You have to remember that every person who installs your mod will make a request like that under the conditions you specify. I have limited the api/tier endpoint to 50 players per query, spamming this endpoint will result in further restrictions to the API.
> 
> Please consider using something that loads on the fly, such as requesting a tier of a user with /api/rankings/<uuid> when they come into render distance. Please also cache this locally for at lease some duration as to not spam the server.

maybe you should use caching instead of doing direct database queries on every request :)
