### ISSUE TITLE
CPVP tags

### ISSUE THREAD

**Issue by RedRat08** [Netiyiy/TierTagger#14]
Will there be any Cpvp tier tag any soon?

**Comment by uku3lig** [comment]
what do you mean by 'tier tag'

**Comment by RedRat08** [comment]
there is no way to show Crystal tiers in mod meny

**Comment by uku3lig** [comment]
????? this doesnt mean anything

**Comment by RedRat08** [comment]
i hope you guse can add that pls

**Comment by RedRat08** [comment]
oh i anderstad now the vanilla shows the cpvp tag sorry for desturbing

**Comment by RedRat08** [comment]
thank you for you mod and i hope it will get better and better. good luck, love your other mods to. bye
