### ISSUE TITLE
No way of showing new tierd players in game

### ISSUE THREAD

**Issue by RedRat08** [Netiyiy/TierTagger#15]
I think the mod have a issue oof showing new tierd player because of the teir website was moved.

**Comment by uku3lig** [comment]
update your mod to 1.6 or above.

**Comment by RedRat08** [comment]
ok

**Comment by RedRat08** [comment]
but is was 1.7, i hade a frend that played with me in sword and he got a tierd in that website and did not show in game
it was not 1.6

**Comment by uku3lig** [comment]
might be related to #13
