### ISSUE TITLE
TierTagger is blocked from McTiers

### ISSUE THREAD

**Issue by uku3lig** [Netiyiy/TierTagger#20]
This is a tracking issue for the current TierTagger outage.

Since June 9th, TierTagger is globally blocked from McTiers, awaiting a pending server upgrade from their side.

**There is nothing I can do to fix this. All me and you reading this can do is wait patiently.**

**Comment by Manered** [comment]
how is it exactly blocked?
maybe try tinkering with the HttpClient options

**Comment by uku3lig** [comment]
@Manered it's blocked by user agent. of course, that can be bypassed without any problem, however that would not solve any issues.

tiertagger is blocked because the current infra of mctiers reportedly cannot handle the load from all the tiertagger users, so trying to circumvent a temporary block while waiting for them would just be a dick move.

therefore, we wait.

**Comment by meltmyeye** [comment]
does this mean it no longer works?

**Comment by uku3lig** [comment]
fixed in latest release

**Comment by Jes-debug** [comment]
really? it still doesnt work for me

**Comment by uku3lig** [comment]
@Jes-debug make sure your mod is up to date
