### ISSUE TITLE
more tiertagger commands

### ISSUE THREAD

**Issue by Purlime** [Netiyiy/TierTagger#22]
so you can change the gamemode with commands so you dont have to go the mod list and find the mod and then change it there, and also why doesnt highest tier not work sometimes, it like still shows their tier in sword even though they have lt3 tiers in other gamemodes, is it because they have more than one highest gamemode ? like more than one that are the same tier, is that why it doesnt show, does it not like do a 50 50 or something

**Comment by Purlime** [comment]
wait should i be putting this as a issue or what idk how this works

**Comment by uku3lig** [comment]
> so you can change the gamemode with commands

the 1.21 version has a keybinding for that

> why doesnt highest tier not work sometimes

as of right now, highest tier is only displayed if the player is not ranked in the selected tier. i'll likely add another option to _always_ have the highest tier soon

**Comment by Purlime** [comment]
why is it only 1.21 tho

**Comment by uku3lig** [comment]
> why is it only 1.21 tho 

many reasons! easier for me to maintain, modern versions usually have more code features, both in Minecraft itself and ukulib, and i also don't necessarily have the time and will to backport everything all the time. 

it also forces people to update to more modern minecraft :)
