### ISSUE TITLE
Update to use Tierlist API

### ISSUE THREAD

**Issue by Matt-MX** [Netiyiy/TierTagger#3]
Hey pvphub have made an API for the tierlist, you might be interested in using it!

https://tiers.pvphub.co/api/list/vanilla
https://tiers.pvphub.co/api/list/netherite-pot
https://tiers.pvphub.co/api/list/pot
https://tiers.pvphub.co/api/list/axe
https://tiers.pvphub.co/api/list/uhc
etc

And for per player stats
https://tiers.pvphub.co/api/player/<username>

e.g
https://tiers.pvphub.co/api/player/ItzRealMe

Stats are read from the tierlist every 1 minute.

**Comment by Matt-MX** [comment]
Implemented in #4

**Comment by Matt-MX** [comment]
FYI the api is down while we transfer to another node for now 😁

**Comment by Matt-MX** [comment]
API currently down to transfer to another node

**Comment by JanCantCode** [comment]
when api back up

**Comment by Matt-MX** [comment]
> when api back up

Not sure, the google sheets api requires us to manually refresh the token every so often, so not clear if it is maintainable.

**Comment by Netiyiy** [comment]
Oh, sorry I did not see this

**Comment by Netiyiy** [comment]
I am not really familiar with GitHub, which is why I don't use it a lot, sorry 😅

**Comment by uku3lig** [comment]
fixed by 66177657c7b3cdc4ac35a24bb50d045db8241d68
