### ISSUE TITLE
[SUGGESTION] Go based off of UUID

### ISSUE THREAD

**Issue by gatolover69** [Netiyiy/TierTagger#6]
This can be very inaccurate, for example, I came across Crey (HT2), but when he was tested, his name was "K1BRENUMBER1FAN". That being said, his tier wasn't in his name. Point being, if someone who was ranked changes their name, and someone else snatches that name, it will mark that person who took the name to be said tier, when they aren't.

Although this is a decent idea, it could be hard, idk, I'm not really a programmer.

**Comment by AshOnDiscord** [comment]
I think the biggest problem with UUIDs, is that the tier list doesn't save UUIDs on their spreadsheet, embeds, or high-result channel messages. If they did, it likely would be relatively easy to implement. Unless they had some sort of db to save it every new ranking, it'd be basically impossible(unless I'm missing smt) unless the tierlist does actually start saving UUID.

**Comment by JanCantCode** [comment]
> I think the biggest problem with UUIDs, is that the tier list doesn't save UUIDs on their spreadsheet, embeds, or high-result channel messages. If they did, it likely would be relatively easy to implement. Unless they had some sort of db to save it every new ranking, it'd be basically impossible(unless I'm missing smt) unless the tierlist does actually start saving UUID.

couldnt you technically just index the tierlist every now and then and compare name differences, so if someone new gets added / their tier changes, you can just get their UUID, and will hopefully slowly reach an accuraccy where everyone has their UUID saved?
obviously you would have to host a backend for that / ask the provider for the api (i think pvphub devs) to implement it

**Comment by uku3lig** [comment]
fixed by using the mctiers.com api, see 66177657c7b3cdc4ac35a24bb50d045db8241d68
